### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '.'

### ISSUE THREAD

**Issue by YanCheer** [hillerlab/TOGA#142]
When I run toga.py, it showed up such error info:
![微信图片_20240126162103](https://github.com/hillerlab/TOGA/assets/7344943/6d46905f-e1e2-42db-837f-b0dd44f12298)

Is there anything wrong with my bed file or the python version?

Thanks a lot!

**Comment by kirilenkobm** [comment]
Hello,

seems like the bed file is corrupted. 

Pls try something like:

```python3
with open("YOUR_BED_FILE", "r") as f:
    line_number = 1
    for line in f:
        fields = line.split("\t")
        if len(fields) >= 6:
            field_6 = fields[5]
            try:
                int(field_6)
            except ValueError:
                print(f"Line {line_number}: {line.strip()}")
        line_number += 1
```

to identify which line exactly is corrupted

**Comment by YanCheer** [comment]
Thank you very much for the reply at yesterday.
After generating the new bed and chain files, I got a new error that I cannot settle down today.

At the `STEP 3: Merge step 2 output`, the running log showed that the pipeline seemed to successfully read but failed to load 
 and combine all the results of transcript annotation, so then generated the empty `merge_chains_output` output results as follows:

>  #### STEP 3: Merge step 2 output
> 
> Reading /projects/yanchen/HiFi_tmp/01.HiFi_Assemble/Assemblies_hifiasm/02.Primary_Assembly_Annotation/TOGA/03.toga_outputs_Run2/TOGA_GRCg7b_Achr1/temp/toga_filt_ref_annot.bed
> merge_chains_output: got data for 44858 transcripts
> merge_chains_output: Loading the results...
> merge_chains_output: There are 0 result files to combine
> merge_chains_output: got 0 keys in chain_genes_data
> merge_chains_output: got 0 keys in chain_raw_data
> merge_chains_output: There were 0 transcript lines and 0 chain lines
> merge_chains_output: chain_genes_data dict reverted, there are 0 keys now
> merge_chains_output: Combining the data...
> merge_chains_output: got combined dict with 0 keys
> merge_chains_output: Writing output to /projects/yanchen/02.Primary_Assembly_Annotation/TOGA/03.toga_outputs_Run2/temp/chain_results_df.tsv
> merge_chains_output: total runtime: 0:00:40.594500

Therefore, at the following step, it reported an `ERROR `info:

> #### STEP 4: Classify chains using gradient boosting model
> 
> Classifying chains
> classify_chains: loaded dataframe of size 0
> classify_chains: total number of transcripts: 0
> classify_chains: 0 rows with spanning chains
> classify_chains: filtered dataset contains 0 records
> classify_chains: omputing additional features...
> classify_chains: WARNING! The final df for classification is empty
> classify_chains: df for single-exon model contains 0 records
> classify_chains: df for multi-exon model contains 0 records
> classify_chains: loading models at /projects/yanchen/softwares/TOGA-1.1.7/models/se_model.dat (SE) and /projects/yanchen/softwares/TOGA-1.1.7/models/me_model.dat (ME)
> /projects/yanchen/softwares/miniconda3_v2/envs/TOGA/lib/python3.9/site-packages/xgboost/core.py:160: UserWarning: [14:33:02] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1705650282415/work/src/common/error_msg.h:80: If you are loading a serialized model (like pickle in Python, RDS in R) or
> configuration generated by an older version of XGBoost, please export the model by calling
> `Booster.save_model` from that version first, then load it back in current version. See:
> 
>     https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html
> 
> for more details about differences between saving model and serializing.
> 
>   warnings.warn(smsg, UserWarning)
> classify_chains: applying models to SE and ME datasets...
> classify_chains: applying -1.0 score to the spanning chains
> classify_chains: applying -2.0 score to the processed pseudogene alignments
> classify_chains: number of processed pseudogene alignments: 0
> classify_chains: arranging the final output
> classify_chains: classification result stats:
> * orthologs: 0
> * paralogs: 0
> * spanning chains: 0
> * processed pseudogenes: 0
> classify_chains: using 0.5 as a threshold to separate orthologs from paralogs
> classify_chains: combining results for 0 individual transcripts
> classify_chains: saving the classification to /projects/yanchen/02.Primary_Assembly_Annotation/TOGA/03.toga_outputs_Run2/temp/trans_to_chain_classes.tsv
> classify_chains: found no classifiable chains for 0 transcripts
> classify_chains: saving these transcripts to: /projects/yanchen/02.Primary_Assembly_Annotation/TOGA/03.toga_outputs_Run2/temp/rejected/classify_chains_rejected.txt
> Chain results file /projects/yanchen/02.Primary_Assembly_Annotation/TOGA/03.toga_outputs_Run2/temp/chain_results_df.tsv is empty! Abort.
> Traceback (most recent call last):
>   File "/projects/yanchen/softwares/TOGA-1.1.7/toga.py", line 1665, in <module>
>     main()
>   File "/projects/yanchen/softwares/TOGA-1.1.7/toga.py", line 1661, in main
>     toga_manager.run()
>   File "/projects/yanchen/softwares/TOGA-1.1.7/toga.py", line 521, in run
>     self.__classify_chains()
>   File "/projects/yanchen/softwares/TOGA-1.1.7/toga.py", line 748, in __classify_chains
>     TogaSanityChecker.check_chains_classified(self.chain_results_df)
>   File "/projects/yanchen/softwares/TOGA-1.1.7/modules/toga_sanity_checks.py", line 217, in check_chains_classified
>     raise ValueError(msg)
> ValueError: Chain results file /projects/yanchen/02.Primary_Assembly_Annotation/TOGA/03.toga_outputs_Run2/temp/chain_results_df.tsv is empty! Abort.


From the last error info, it showed me the point was at the chain results file `chain_results_df.tsv` produced by the pipeline.
Do you have any idea where the error is hidden behind?

Thank you very much for provide such a tiny help for me!!!!!

**Comment by MichaelHiller** [comment]
Hi, 

sorry, if we were not able to fix the TOGA1 problem you describe. 

We are now releasing TOGA2 for beta-testing https://github.com/hillerlab/TOGA2
TOGA2 is much faster and 300X less memory-demanding. This will likely solve the problem you describe. 

There is an Apptainer containerized version that you can use if you want to run it on a multi-core server.

If you want to run it on a compute cluster using Slurm, pls install it locally.
Instructions are on github.

Could you pls try if TOGA2 works for you?
If not, pls open a TOGA2 github issue and we will respond.

Thx
Michael
