### ISSUE TITLE
ValueError: Chain results file  chain_results_df.tsv is empty! Abort.

### ISSUE THREAD

**Issue by txfc** [hillerlab/TOGA#152]
Dear author
I am trying to use TOGA for gene annotation, I went through all the steps as presented in the GitHub and it is doing well even for the first test case in which I got the same output as predicted.
However, for the final test case, at the end of STEP 4, I get this "chain_results_df.tsv Empty! Abort." error.
Actually, I have already installed twobitreader and scikit-learn by pip, I do not know why it reported they are not installed.

```
#### Initiating TOGA class ####
# python interpreter path: /home/duanying/miniconda3/bin/python3
# python interpreter version: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]
Version 1.1.8.dev
Commit: 97eb5a17ce76fccd9858b2ed738c51cd661292aa
Branch: master

# Python package versions
* twobitreader: unknown version
* networkx: 3.1
* pandas: 2.1.4
* numpy: 1.26.2
* xgboost: 2.0.3
! scikit-learn: Not installed - will try to install
* joblib: 1.3.2
* h5py: 3.10.0
Calling cmd:
/mnt/data/duanying/bio_softer/TOGA/./configure.sh

Compiling C code...
Model found
CESAR installation found
Command finished with exit code 0.
Does it work?
Calling cmd:
/mnt/data/duanying/bio_softer/TOGA/./modules/chain_score_filter test_input/hg38.mm10.chr11.chain 15000 > /mnt/data/duanying/bio_softer/TOGA/test/temp/genome_alignment.chain

Command finished with exit code 0.
Writing isoforms data for 3674 transcripts.
Found 455 sequences in /mnt/data/duanying/bio_softer/TOGA/test_input/hg38.2bit
Found 455 sequences in /mnt/data/duanying/bio_softer/TOGA/test_input/hg38.2bit
Found 66 sequences in /mnt/data/duanying/bio_softer/TOGA/test_input/mm10.2bit
Saving output to /mnt/data/duanying/bio_softer/TOGA/test
Arguments stored in /mnt/data/duanying/bio_softer/TOGA/test/project_args.json


#### STEP 0: making chain and bed file indexes

Started chain indexing...
chain_bst_index: indexing 79183 chains
chain_bst_index: Saved chain /mnt/data/duanying/bio_softer/TOGA/test/temp/genome_alignment.chain index to /mnt/data/duanying/bio_softer/TOGA/test/temp/genome_alignment.bst
Started bed file indexing...
bed_hdf5_index: indexed 3674 transcripts


#### STEP 1: Generate extract chain features jobs

Calling cmd:
/mnt/data/duanying/bio_softer/TOGA/./split_chain_jobs.py /mnt/data/duanying/bio_softer/TOGA/test/temp/genome_alignment.chain /mnt/data/duanying/bio_softer/TOGA/test/temp/toga_filt_ref_annot.bed /mnt/data/duanying/bio_softer/TOGA/test/temp/toga_filt_ref_annot.hdf5 --log_file /mnt/data/duanying/bio_softer/TOGA/test/toga_2024_03_17_at_07_38.log --parallel_logs_dir /mnt/data/duanying/bio_softer/TOGA/test/temp_logs --jobs_num 100 --jobs /mnt/data/duanying/bio_softer/TOGA/test/temp/chain_classification_jobs --jobs_file /mnt/data/duanying/bio_softer/TOGA/test/temp/chain_class_jobs_combined --results_dir /mnt/data/duanying/bio_softer/TOGA/test/temp/chain_classification_results --rejected /mnt/data/duanying/bio_softer/TOGA/test/temp/rejected/SPLIT_CHAIN_REJ.txt

split_chain_jobs: Use bed file /mnt/data/duanying/bio_softer/TOGA/test/temp/toga_filt_ref_annot.bed and chain file /mnt/data/duanying/bio_softer/TOGA/test/temp/genome_alignment.chain
split_chain jobs: the run data overview is:

* vv: False
* jobs: /mnt/data/duanying/bio_softer/TOGA/test/temp/chain_classification_jobs
* results_dir: /mnt/data/duanying/bio_softer/TOGA/test/temp/chain_classification_results
* errors_dir: None
* chain_file: /mnt/data/duanying/bio_softer/TOGA/test/temp/genome_alignment.chain
* bed_file: /mnt/data/duanying/bio_softer/TOGA/test/temp/toga_filt_ref_annot.bed
* index_file: /mnt/data/duanying/bio_softer/TOGA/test/temp/genome_alignment.chain_ID_position
* job_size: None
* jobs_num: 100
* bed_index: /mnt/data/duanying/bio_softer/TOGA/test/temp/toga_filt_ref_annot.hdf5
* jobs_file: /mnt/data/duanying/bio_softer/TOGA/test/temp/chain_class_jobs_combined
* ref: hg38
* on_cluster: True
split_chain_jobs: searching for intersections between reference transcripts and chains
split_chain_jobs: chains-to-transcripts dict contains 50186 records
split_chain_jobs: skipped 0 transcripts that do not intersect any chain
split_chain_jobs: preparing 50186 commands
split_chain_jobs: command size of 502 for each cluster job
split_chain_jobs: results in 100 cluster jobs
split_chain_jobs: estimated time: 0:00:00.626798
Command finished with exit code 0.


#### STEP 2: Extract chain features: parallel step

Extracting chain features, project name: chain_feats__test_at_1710661095
Project path: /mnt/data/duanying/bio_softer/TOGA/./nextflow_logs/chain_feats__test_at_1710661095
Selected parallelization strategy: nextflow
Parallel manager: pushing job nextflow /mnt/data/duanying/bio_softer/TOGA/execute_joblist.nf --joblist /mnt/data/duanying/bio_softer/TOGA/test/temp/chain_class_jobs_combined -c nextflow_config_files/extract_chain_features_queue.nf
Logs from individual chain runner jobs are show below


#### STEP 3: Merge step 2 output

Reading /mnt/data/duanying/bio_softer/TOGA/test/temp/toga_filt_ref_annot.bed
merge_chains_output: got data for 3674 transcripts
merge_chains_output: Loading the results...
merge_chains_output: There are 0 result files to combine
merge_chains_output: got 0 keys in chain_genes_data
merge_chains_output: got 0 keys in chain_raw_data
merge_chains_output: There were 0 transcript lines and 0 chain lines
merge_chains_output: chain_genes_data dict reverted, there are 0 keys now
merge_chains_output: Combining the data...
merge_chains_output: got combined dict with 0 keys
merge_chains_output: Writing output to /mnt/data/duanying/bio_softer/TOGA/test/temp/chain_results_df.tsv
merge_chains_output: total runtime: 0:00:07.901663


#### STEP 4: Classify chains using gradient boosting model

Classifying chains
classify_chains: loaded dataframe of size 0
classify_chains: total number of transcripts: 0
classify_chains: 0 rows with spanning chains
classify_chains: filtered dataset contains 0 records
classify_chains: omputing additional features...
classify_chains: WARNING! The final df for classification is empty
classify_chains: df for single-exon model contains 0 records
classify_chains: df for multi-exon model contains 0 records
classify_chains: loading models at /mnt/data/duanying/bio_softer/TOGA/./models/se_model.dat (SE) and /mnt/data/duanying/bio_softer/TOGA/./models/me_model.dat (ME)
classify_chains: applying models to SE and ME datasets...
classify_chains: applying -1.0 score to the spanning chains
classify_chains: applying -2.0 score to the processed pseudogene alignments
classify_chains: number of processed pseudogene alignments: 0
classify_chains: arranging the final output
classify_chains: classification result stats:
* orthologs: 0
* paralogs: 0
* spanning chains: 0
* processed pseudogenes: 0
classify_chains: using 0.5 as a threshold to separate orthologs from paralogs
classify_chains: combining results for 0 individual transcripts
classify_chains: saving the classification to /mnt/data/duanying/bio_softer/TOGA/test/temp/trans_to_chain_classes.tsv
classify_chains: found no classifiable chains for 0 transcripts
classify_chains: saving these transcripts to: /mnt/data/duanying/bio_softer/TOGA/test/temp/rejected/classify_chains_rejected.txt
Chain results file /mnt/data/duanying/bio_softer/TOGA/test/temp/chain_results_df.tsv is empty! Abort.
Traceback (most recent call last):
  File "/mnt/data/duanying/bio_softer/TOGA/./toga.py", line 1600, in <module>
    main()
  File "/mnt/data/duanying/bio_softer/TOGA/./toga.py", line 1596, in main
    toga_manager.run()
  File "/mnt/data/duanying/bio_softer/TOGA/./toga.py", line 510, in run
    self.__classify_chains()
  File "/mnt/data/duanying/bio_softer/TOGA/./toga.py", line 737, in __classify_chains
    TogaSanityChecker.check_chains_classified(self.chain_results_df)
  File "/mnt/data/duanying/bio_softer/TOGA/modules/toga_sanity_checks.py", line 217, in check_chains_classified
    raise ValueError(msg)
ValueError: Chain results file /mnt/data/duanying/bio_softer/TOGA/test/temp/chain_results_df.tsv is empty! Abort.

```
This is the log from nextflow_logs
```
N E X T F L O W  ~  version 23.10.0
ERROR ~ Error executing process > 'execute_jobs (77)'
.......
.......
Caused by:
  java.io.IOException: Cannot run program "sbatch" (in directory "/mnt/data/duanying/bio_softer/TOGA/nextflow_logs/work/0d/a53de4e128c47ddc2532b94e9ca0ed"): error=2, No such file or directory

Command executed:

  sbatch .command.run

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /mnt/data/duanying/bio_softer/TOGA/nextflow_logs/work/0d/a53de4e128c47ddc2532b94e9ca0ed

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

```

**Comment by austinchipps** [comment]
I'm experiencing the same issue, including the message about twobitreader having an unknown version and scikit-learn not being installed. My nextflow_logs show the same error messages.

**Comment by AryehMiller** [comment]
Hi both, are you providing the full path to `${nextflow_config_dir}` containing the relevant nextflow files in your `./toga.py` command?

**Comment by austinchipps** [comment]
Hey @AryehMiller, 

Yes - I have the path to the directory with the nextflow config files in the toga.py command.

**Comment by txfc** [comment]
Hi @austinchipps，
I suggest you remove the --nc in your command, if you run it on your PC or Server.  Maybe because you did not install Slurm on your system.
But I'm unsure how to resolve the issue of scikit-learn not being installed.

**Comment by SomePersonSomeWhereInTheWorld** [comment]
I'm definitely on Slurm and getting this issue:

```
classify_chains: using 0.5 as a threshold to separate orthologs from paralogs
classify_chains: combining results for 0 individual transcripts
classify_chains: saving the classification to /burg/home/rk3199/TOGA/test/temp/trans_to_chain_classes.tsv
classify_chains: found no classifiable chains for 0 transcripts
classify_chains: saving these transcripts to: /burg/home/rk3199/TOGA/test/temp/rejected/classify_chains_rejected.txt
Chain results file /burg/home/rk3199/TOGA/test/temp/chain_results_df.tsv is empty! Abort.
Traceback (most recent call last):
  File "/path/to/me/TOGA/./toga.py", line 1600, in <module>
    main()
  File "/path/to/me/TOGA/./toga.py", line 1596, in main
    toga_manager.run()
  File "/path/to/me/TOGA/./toga.py", line 510, in run
    self.__classify_chains()
  File "/path/to/me/TOGA/./toga.py", line 737, in __classify_chains
    TogaSanityChecker.check_chains_classified(self.chain_results_df)
  File "/path/to/me/TOGA/modules/toga_sanity_checks.py", line 217, in check_chains_classified
    raise ValueError(msg)
ValueError: Chain results file /path/to/me/TOGA/test/temp/chain_results_df.tsv is empty! Abort.
```
