### ISSUE TITLE
Some nextflow processes died

### ISSUE THREAD

**Issue by molinfzlvvv** [hillerlab/TOGA#161]
Hi,I have a few problems, hope to get your help.

my command is :
./toga.py /home/TOGAInput/query/hg38.H.g.final.chain /home/TOGAInput/human_hg38/toga.transcripts.bed /home/TOGA/hg38.2bit /home/TOGA/query/H.g.2bit --kt --pn /opt/synData2/Hg -i /home/TOGAInput/human_hg38/toga.isoforms.tsv --nc /home/TOGA/nextflow_config_files --cb 10,100 --cjn 300 --u12 /home/TOGAInput/human_hg38/toga.U12introns.tsv --ms -q

When I was working on CESAR job, the following error occurred:

Compiling C code...
Model found
CESAR installation found
Traceback (most recent call last):
  File "/home/TOGA/./toga.py", line 1600, in <module>
    main()
  File "/home/TOGA/./toga.py", line 1596, in main    toga_manager.run()
  File "/home/TOGA/./toga.py", line 530, in run
    self.__check_cesar_completeness()  File "/home/TOGA/./toga.py", line 1088, in __check_cesar_completeness
    monitor_jobs(jobs_managers, die_if_sc_1=True)  File "/home/TOGA/modules/parallel_jobs_manager_helpers.py", line 36, in monitor_jobs
    raise AssertionError(err)
AssertionError: Error! Some para/nextflow processes died!

The log file section is as follows：

Checking whether all CESAR results are complete
1 CESAR jobs crashed, trying to run again...
!!RERUN CESAR JOBS: Pushing 1 jobs into None GB queue
Selected parallelization strategy: nextflow
Parallel manager: pushing job nextflow /home/fengzl22/TOGA/execute_joblist.nf --joblist /opt/synData2/fengzl22/Hglaber2/_cesar_rerun_batch_None -c /opt/synData2/fengzl22/Hglaber2/temp/cesar_config_16_queue.nf
Monitoring CESAR jobs rerun
## Stated polling cluster jobs until they done
Polling iteration 0; already waiting 0 seconds.
Polling iteration 1; already waiting 60 seconds.
Polling iteration 2; already waiting 120 seconds.
Polling iteration 3; already waiting 180 seconds.
.......
Polling iteration 48; already waiting 2880 seconds.
Polling iteration 49; already waiting 2940 seconds.
### CESAR jobs done ###

It's worth noting that this error occurs frequently. Sometimes, running it a second time with the same instructions might work, but each run often requires a significant time investment. Do you have any suggestions for addressing this issue?

Best regards!

**Comment by kirilenkobm** [comment]
Hi! 
I am sorry for that, feels like I implemented quite aggressive strategy here.
After TOGA tries to execute its CESAR jobs, it collects those that crashed (which may happen due to a variety of reasons) and pushes them again.
I any job dies, the TOGA process dies as well.
Will be disabled in the next commit (in a couple of minutes)

**Comment by molinfzlvvv** [comment]
Hi！
Thank for your response. Could you help to look at this problem again? This bothered me for a long time.
https://github.com/hillerlab/TOGA/issues/140#issuecomment-2126045291
My task has been running for ten days, and it has been in the process called "### STEP 7: Execute CESAR jobs: parallel step".Paradoxically, it seems to be working just fine, because the log file keeps growing.

In fact, I applied for a node with 40 cpus, and then I changed the nextflow setting to process.cpus = 40 // SLURM config file for CESAR jobs, but it actually looks like it only utilizes 2 cpus. I don't know why it's not using all the resources, is that why it's so slow?

If you can suggest any commands to speed up the process, I would really appreciate it.

**Comment by molinfzlvvv** [comment]
Hi!  I hope this email finds you well. My name is Molin,  a PhD candidate
in Lanzhou University.  I'm sorry to bother you so many times. it is met
the difficult to solve the problem.
My TOGA task has been running for ten days, and it has been in the process
called "### STEP 7: Execute CESAR jobs: parallel step".Paradoxically, it
seems to be working just fine, because the log file keeps growing.
In fact, I applied for a node with 40 cpus, and then I changed the nextflow
setting to "process.cpus = 40 // SLURM config file for CESAR jobs", but it
actually looks like it only utilizes 2 cpus. I don't know why it's not
using all the resources, is that why it's so slow?

my command is :
./toga.py /opt/DWR.chain /home/toga.transcripts.bed /home/hg38.2bit
/opt/DWR.2bit --kt --pn /opt/DWR -i /home/toga.isoforms.tsv --nc
/home/nextflow_config_files --cb 10,100 --cjn 300 --u12
/home/toga.U12introns.tsv --ms -q

The log shows :
### STEP 7: Execute CESAR jobs: parallel step
Pushing 2 CESAR job lists
Pushing memory bucket 10Gb to the executor
Selected parallelization strategy: nextflow
Parallel manager: pushing job nextflow /home/TOGA/execute_joblist.nf --joblist
/opt/synData2/gene_loss/DWR/temp/cesar_joblist_queue_10.txt -c
/opt/synData2/gene_loss/DWR/temp/cesar_config_10_queue.nf
Pushing memory bucket 100Gb to the executor
Selected parallelization strategy: nextflow
Parallel manager: pushing job nextflow /home/TOGA/execute_joblist.nf --joblist
/opt/synData2/gene_loss/DWR/temp/cesar_joblist_queue_100.txt -c
/opt/synData2/gene_loss/DWR/temp/cesar_config_100_queue.nf
## Stated polling cluster jobs until they done
Polling iteration 0; already waiting 0 seconds.
Polling iteration 1; already waiting 60 seconds.
.......
Polling iteration 7882; already waiting 472920 seconds.
Polling iteration 7883; already waiting 472980 seconds.

I really don't know what causes it. If you can suggest any commands to
speed up the process, I would really appreciate it. Looking forward to your
reply.

Best regards!


Bogdan Kirilenko ***@***.***> 于2024年5月27日周一 00:07写道：

**Comment by molinfzlvvv** [comment]
Hi! @kirilenkobm 

I am very sorry to bother you many times, so far I have not successfully run an instance. I actually tried a lot, and I couldn't commit it to the slurm system, it kept reporting errors. So now I'm running TOGA on a master node with 40 cores, divided into two buckets based on memory(--cn 10,100). I expect to be able to use all the CPUs at CESAR, but I'm only using two CPUs. It's working normally just too slow, and it seems like it can only run one and then move on to the next at CESAR, which has been working for over a week. Do you have any suggestions for this, which I would appreciate very much

By the way, my nextflow is 21.10.6.5660 and I git clone TOGA directly.Looking forward to your reply.

Best regards!

**Comment by MichaelHiller** [comment]
Hi, 

sorry, if we were not able to fix the TOGA1 problem you describe. 

We are now releasing TOGA2 for beta-testing https://github.com/hillerlab/TOGA2
TOGA2 is much faster and 300X less memory-demanding. This will likely solve the CESAR problem you describe. 

There is an Apptainer containerized version that you can use if you want to run it on a multi-core server.

If you want to run it on a compute cluster using Slurm, pls install it locally.
Instructions are on github.

Could you pls try if TOGA2 works for you?
If not, pls open a TOGA2 github issue and we will respond.

Thx
Michael
