### ISSUE TITLE
Errors，When I install TOGA <./run_test.sh micro>

### ISSUE THREAD

**Issue by chemy-cm** [hillerlab/TOGA#24]
The last step got wrong
```shell
#### STEP 10: Create orthology relationships table

Traceback (most recent call last):
  File "./toga.py", line 1270, in <module>
    main()
  File "./toga.py", line 1266, in main
    toga_manager.run()
  File "./toga.py", line 603, in run
    self.__orthology_type_map()
  File "./toga.py", line 1054, in __orthology_type_map
    get_query_isoforms_data(self.query_annotation, query_isoforms_file, save_genes_track=query_gene_spans)
  File "/data/cm/software/TOGA/modules/make_query_isoforms.py", line 243, in get_query_isoforms_data
    components = get_graph_components(conn_graph)
  File "/data/cm/software/TOGA/modules/common.py", line 251, in get_graph_components
    nx_v = float(nx.__version__)
ValueError: could not convert string to float: '2.6.2'
```

**Comment by kirilenkobm** [comment]
Hi,

Thank you for reporting the issue,
In the next commit it will be solved.

**Comment by kirilenkobm** [comment]
It's fixed, pls update the code with git pull
