### ISSUE TITLE
AttributeError: module 'networkx' has no attribute 'connected_component_subgraphs'

### ISSUE THREAD

**Issue by fantasticair** [hillerlab/TOGA#3]
Hi,
I have install the `networkx` module, but get this error.
```
./run_test.sh micro
Requirement already satisfied: twobitreader in /home/.local/lib/python3.7/site-packages (from -r ./requirements.txt (line 1)) (3.1.7)
Requirement already satisfied: networkx in /home/anaconda3/lib/python3.7/site-packages (from -r ./requirements.txt (line 2)) (2.4)
Requirement already satisfied: pandas in /home/anaconda3/lib/python3.7/site-packages (from -r ./requirements.txt (line 3)) (0.25.2)
Requirement already satisfied: xgboost in /home/.local/lib/python3.7/site-packages (from -r ./requirements.txt (line 4)) (1.1.1)
Requirement already satisfied: scikit-learn in /home/anaconda3/lib/python3.7/site-packages (from -r ./requirements.txt (line 5)) (0.21.3)
Requirement already satisfied: joblib in /home/anaconda3/lib/python3.7/site-packages (from -r ./requirements.txt (line 6)) (0.13.2)
Requirement already satisfied: bsddb3 in /home/anaconda3/lib/python3.7/site-packages/bsddb3-6.2.6-py3.7-linux-x86_64.egg (from -r ./requirements.txt (line 7)) (6.2.6)
Requirement already satisfied: decorator>=4.3.0 in /home/anaconda3/lib/python3.7/site-packages (from networkx->-r ./requirements.txt (line 2)) (4.4.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /home/anaconda3/lib/python3.7/site-packages (from pandas->-r ./requirements.txt (line 3)) (2.8.0)
Requirement already satisfied: pytz>=2017.2 in /home/anaconda3/lib/python3.7/site-packages (from pandas->-r ./requirements.txt (line 3)) (2019.3)
Requirement already satisfied: numpy>=1.13.3 in /home/anaconda3/lib/python3.7/site-packages (from pandas->-r ./requirements.txt (line 3)) (1.18.1)
Requirement already satisfied: scipy in /home/anaconda3/lib/python3.7/site-packages (from xgboost->-r ./requirements.txt (line 4)) (1.3.1)
Requirement already satisfied: six>=1.5 in /home/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas->-r ./requirements.txt (line 3)) (1.12.0)
python packages successfully installed
Model found
CESAR installation found
Compiling C code...
.
.
.
Merging CESAR output to make final fasta and pre-final bed files.
Saving the output
Calling gene loss summary
Elapsed: 0:00:00.000822
Traceback (most recent call last):
  File "./toga.py", line 724, in <module>
    main()
  File "./toga.py", line 720, in main
    toga_manager.run()
  File "./toga.py", line 379, in run
    self.__orthology_type_map()
  File "./toga.py", line 598, in __orthology_type_map
    get_query_isoforms_data(self.query_annotation, query_isoforms_file, save_genes_track=query_gene_spans)
  File "/home/software/TOGA/modules/make_query_isoforms.py", line 230, in get_query_isoforms_data
    components = list(nx.connected_component_subgraphs(conn_graph))
AttributeError: module 'networkx' has no attribute 'connected_component_subgraphs'
```

**Comment by fantasticair** [comment]
OK，I have solved this error.
The `connected_component_subgraphs`  in `networkx` still present up till 2.3, and removed in 2.4.
using this command to solve.
`pip install --force-reinstall networkx==2.3`

**Comment by kirilenkobm** [comment]
Hi and thanks for the report!

I'll make TOGA compatible with both <2.4 and >=2.4 versions of networkx for now.
Making user to downgrade a package is not the best possible solution.
