### ISSUE TITLE
AssertionError     STEP 10: Create orthology relationships table.    

### ISSUE THREAD

**Issue by 002-two** [hillerlab/TOGA#33]
Hi!
When running the program I got the following error at STEP 10.
How do I fix it?
Thanks!

Calling orthology_type_map...
Traceback (most recent call last):
  File "/data/01/user191/anxuan/genome.compare/05.TOGA/./TOGA/toga.py", line 1965, in <module>
    main()
  File "/data/01/user191/anxuan/genome.compare/05.TOGA/./TOGA/toga.py", line 1961, in main
    toga_manager.run()
  File "/data/01/user191/anxuan/genome.compare/05.TOGA/./TOGA/toga.py", line 778, in run
    self.__orthology_type_map()
  File "/data/01/user191/anxuan/genome.compare/05.TOGA/./TOGA/toga.py", line 1605, in __orthology_type_map
    orthology_type_map(
  File "/data/01/user191/anxuan/genome.compare/05.TOGA/TOGA/modules/orthology_type_map.py", line 586, in orthology_type_map
    que_transcripts_all = extract_names_from_bed(que_bed)  # list of query transcripts
  File "/data/01/user191/anxuan/genome.compare/05.TOGA/TOGA/modules/orthology_type_map.py", line 126, in extract_names_from_bed
    assert len(names) > 0  # if not, there is a huge bug
AssertionError

**Comment by 002-two** [comment]
![image](https://user-images.githubusercontent.com/77915435/187119935-43facf82-021f-4e8b-b55d-2df01a12560f.png)

**Comment by kirilenkobm** [comment]
@002-two 

This is interesting.
Please reopen the issue if it is still relevant.

If so, please send me the following files from the affected TOGA output:
- reference annotation in bed format
- reference isoforms (tsv, if exists)
- query_annotation.bed
- orthology_classification.tsv
- query_isoforms.tsv (if exists)
- temp/paralogs.txt (if exists)
- loss_summ_data.tsv
- ref_orphan_transcripts.txt (if exists)
- orthology_scores.tsv

Then I will be able to reproduce the issue
