### ISSUE TITLE
Error in step 4 : TypeError: NoneType.__new__(X): X is not a type object (NoneType)

### ISSUE THREAD

**Issue by chklopp** [hillerlab/TOGA#34]
Hi,

It is my first test and TOGA seems to work find until step 4.

```
#### STEP 3: Merge step 2 output

Merging chain output...
Reading TOGA/maternal/temp/toga_filt_ref_annot.bed

Got data for 45026 genes

Loading the results...

There are 99 result files to combine

Got 1828 keys in chain_genes_data

Got 2862 keys in chain_raw_data

There were 2862 genes lines and 2862 chain lines

chain_genes_data dict reverted, there are 44952 keys now

Combining the data...

Got combined dict with 44952 keys

Writing output to TOGA/maternal/temp/chain_results_df.tsv

Estimated_time: 0:01:18.432165
#### STEP 4: Classify chains using gradient boosting model

Decision tree in progress...
Loading dataset...

Load and apply model

Traceback (most recent call last):
  File "TOGA/./toga.py", line 1967, in <module>
    main()
  File "TOGA/./toga.py", line 1963, in main
    toga_manager.run()
  File "TOGA/./toga.py", line 744, in run
    self.__classify_chains()
  File "TOGA/./toga.py", line 928, in __classify_chains
    classify_chains(
  File "TOGA/modules/classify_chains.py", line 131, in classify_chains
    se_model = joblib.load(se_model_path)
  File "/home/klopp/.local/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/klopp/.local/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3/lib/python3.9/pickle.py", line 1513, in load_newobj
    obj = cls.__new__(cls, *args)
TypeError: NoneType.__new__(X): X is not a type object (NoneType)

```

What could I try?

**Comment by chklopp** [comment]
The error was coming from the use of the wrong python version which did not have xgboost correctly installed.
